export const GETSEARCHITEMS = {
    GET_SEARCH_ITEMS_SUCCESS : 'GET_SEARCH_ITEMS_SUCCESS',
    GET_SEARCH_ITEMS_ISLOADING: 'GET_SEARCH_ITEMS_ISLOADING',
    GET_SEARCH_ITEMS_ERROR : 'GET_SEARCH_ITEMS_ERROR',
}
export const HANDLESEARCH = {
    HANDLE_SEARCH_NAME : 'HANDLE_SEARCH_NAME',
    HANDLE_SEARCH_YEAR : 'HANDLE_SEARCH_YEAR',
    HANDLE_SEARCH_TYPE : 'HANDLE_SEARCH_TYPE',
}